extends Node
## 한국어/영어 문자열 표. Loc.t("키") 로 쓴다. 없는 키는 키 이름을 그대로 돌려준다.

var lang := "ko"

const S := {
	# 타이틀/공통
	"tagline": ["송골매의 삶 — 하늘에서 내리꽂는 총알", "Life of a Peregrine — a bullet from the sky"],
	"t_continue": ["이어하기", "Continue"],
	"t_new": ["새로운 삶", "New Life"],
	"t_settings": ["설정", "Settings"],
	"t_controls": ["조작법", "Controls"],
	"t_credits": ["만든 이들", "Credits"],
	"t_quit": ["종료", "Quit"],
	"map_isl_seabird": ["바닷새섬", "Seabird Rock"],
	"map_isl_seals": ["물범 모래톱", "Seal Sands"],
	"map_isl_bats": ["박쥐섬", "Bat Isle"],
	"footer": ["마우스+키보드 / 게임패드", "Mouse+Keyboard / Gamepad"],
	"back": ["뒤로", "Back"],
	"loading": ["섬을 만드는 중...", "Shaping the island..."],
	"saved": ["저장했습니다", "Game saved"],
	"screenshot_saved": ["스크린샷 저장: %s", "Screenshot saved: %s"],
	"record_unlocked": ["기록 달성 — %s", "Record unlocked — %s"],
	"t_records": ["기록", "Records"],
	"records_count": ["%d / %d 달성", "%d / %d unlocked"],
	# 새 게임
	"ng_title": ["새로운 삶", "A New Life"],
	"ng_name": ["이름", "Name"],
	"ng_sex": ["성별", "Sex"],
	"ng_diff": ["난이도", "Difficulty"],
	"ng_male": ["수컷", "Tiercel (male)"],
	"ng_female": ["암컷", "Falcon (female)"],
	"ng_male_desc": ["작고 가볍다. 더 민첩하게 선회하고 스태미나 회복이 빠르다. 오리 같은 큰 먹잇감은 빠르게 내리꽂아야 쓰러뜨릴 수 있다.", "Smaller and lighter. Turns sharper. Big prey like ducks needs a very fast strike."],
	"ng_female_desc": ["수컷보다 3분의 1쯤 크다. 힘이 세서 느린 속도로도 큰 먹잇감을 쓰러뜨리지만 선회가 둔하다.", "About a third larger than the male. Strong enough to down big prey at lower speed, but turns wider."],
	"ng_normal": ["보통", "Normal"],
	"ng_wild": ["야생", "Wild"],
	"ng_normal_desc": ["치명상을 입어도 기절했다가 둥지에서 깨어난다. 굶주림과 늙음은 피할 수 없다.", "Fatal crashes knock you out and you wake at the eyrie. Hunger and age still kill."],
	"ng_wild_desc": ["한 번의 실수가 곧 죽음. 살아남은 자식이 있어야 혈통을 이어갈 수 있다.", "One mistake is death. Only living offspring can carry the bloodline on."],
	"ng_start": ["하늘로", "Take to the sky"],
	"ng_start_over": ["기존 삶을 지우고 시작", "Overwrite save and start"],
	# 일시정지
	"p_title": ["일시정지", "Paused"],
	"p_resume": ["계속하기", "Resume"],
	"p_map": ["지도", "Map"],
	"p_save_quit": ["저장하고 타이틀로", "Save & Quit to Title"],
	"p_quit": ["저장하고 종료", "Save & Exit"],
	"map_hint": ["[M] 또는 [Esc] 닫기", "[M] or [Esc] to close"],
	"map_village": ["어촌", "Village"],
	"map_bay": ["갯벌", "Mudflats"],
	"map_fields": ["들판", "Fields"],
	"map_cliffs": ["해안 절벽", "Sea Cliffs"],
	"map_lighthouse": ["등대", "Lighthouse"],
	# 설정
	"s_mouse": ["마우스 감도", "Mouse sensitivity"],
	"s_invert": ["상하 반전", "Invert Y"],
	"s_master": ["전체 볼륨", "Master volume"],
	"s_music": ["음악", "Music"],
	"s_sfx": ["효과음", "Sound effects"],
	"s_amb": ["바람·파도", "Wind & waves"],
	"s_fx": ["속도감 화면 효과", "Speed screen effects"],
	"s_shake": ["화면 흔들림", "Screen shake"],
	"s_killcam": ["완벽한 일격 연출", "Perfect-strike cinematic"],
	"s_hints": ["도움말 표시", "Show hints"],
	"s_quality": ["그래픽 품질", "Graphics quality"],
	"s_q_low": ["낮음", "Low"],
	"s_q_mid": ["보통", "Medium"],
	"s_q_high": ["높음", "High"],
	"s_fullscreen": ["전체 화면", "Fullscreen"],
	"s_vsync": ["수직 동기화", "V-Sync"],
	"s_day": ["하루 길이", "Day length"],
	"s_day_short": ["짧게 (6분)", "Short (6 min)"],
	"s_day_normal": ["보통 (8분)", "Normal (8 min)"],
	"s_day_long": ["길게 (12분)", "Long (12 min)"],
	"s_lang": ["언어", "Language"],
	# 조작법
	"ctrl_mouse": ["마우스 / 왼쪽 스틱", "Mouse / Left stick"],
	"ctrl_mouse_d": ["바라보는 곳으로 날아간다", "Fly where you look"],
	"ctrl_flap": ["W / 우클릭 / A", "W / Right click / A"],
	"ctrl_flap_d": ["날갯짓 (스태미나 소모)", "Flap (uses stamina)"],
	"ctrl_tuck": ["스페이스 / 좌클릭 유지 / RT", "Space / Hold left click / RT"],
	"ctrl_tuck_d": ["날개 접기 — 급강하(STOOP)", "Tuck wings — the STOOP"],
	"ctrl_brake": ["S / LB", "S / LB"],
	"ctrl_brake_d": ["날개 펼쳐 감속 (착지 전에)", "Flare to slow down (before landing)"],
	"ctrl_roll": ["A / D", "A / D"],
	"ctrl_roll_d": ["좌우로 돌기. 빠르게 두 번 누르면 옆으로 구르기 (구애 비행 가산점)", "Turn left/right. Double-tap to barrel roll (courtship bonus)"],
	"prompt_thermal": ["상승기류 — 마우스에서 손을 떼면 알아서 빙빙 돈다", "Thermal — let go of the mouse to circle automatically"],
	"prompt_autocircle": ["자동 선회 중 ▲ %.0f m/s  (마우스를 움직이면 풀림)", "Auto-circling ▲ %.0f m/s  (move the mouse to take over)"],
	"ctrl_eye": ["C / Shift / LT 유지", "Hold C / Shift / LT"],
	"ctrl_eye_d": ["매의 눈 — 먼 먹잇감, 약한 개체(빨간 원), 상승기류 보기", "Falcon eye — distant prey, weak ones (red ring), thermals"],
	"ctrl_land": ["E / B", "E / B"],
	"ctrl_land_d": ["착지 / 둥지 메뉴 / 날아오르기", "Land / Eyrie menu / Take off"],
	"ctrl_eat": ["Q / X", "Q / X"],
	"ctrl_eat_d": ["먹기 (작은 새는 날면서, 큰 새는 앉아서)", "Eat (small prey in flight, big prey perched)"],
	"ctrl_drop": ["F / Y", "F / Y"],
	"ctrl_drop_d": ["먹이 떨어뜨리기 — 짝에게 선물, 새끼 교육, 둥지 배달", "Drop prey — gift to mate, teach young, deliver"],
	"ctrl_call": ["R / RB", "R / RB"],
	"ctrl_call_d": ["울음 — 짝을 부른다", "Call — summon your mate"],
	"ctrl_map": ["M / Tab", "M / Tab"],
	"ctrl_map_d": ["지도", "Map"],
	"ctrl_pause": ["Esc / Start", "Esc / Start"],
	"ctrl_pause_d": ["일시정지", "Pause"],
	"ctrl_view": ["V / R3", "V / R3"],
	"ctrl_view_d": ["시점 전환 (1인칭 / 3인칭)", "Toggle first / third person"],
	"view_first": ["1인칭 시점", "First-person view"],
	"view_third": ["3인칭 시점", "Third-person view"],
	"ctrl_misc": ["F11 / F12", "F11 / F12"],
	"ctrl_misc_d": ["전체 화면 전환 / 스크린샷", "Toggle fullscreen / Screenshot"],
	"ctrl_tip": ["팁: 높이가 곧 속도다. 상승기류로 높이 올라간 뒤 날개를 접고, ◇ 예측 지점을 노려라. 위에서 뒤로 내리꽂으면 먹잇감이 거의 알아채지 못한다. 방향을 틀 때마다 속도를 잃으니 처음부터 잘 겨눠라.", "Tip: altitude is speed. Climb in a thermal, tuck, and aim for the ◇ lead mark. Prey rarely sees a stoop from above and behind. Every correction bleeds speed, so aim early."],
	# HUD
	"hud_hp": ["체력", "Health"],
	"hud_food": ["포만감", "Food"],
	"hud_stam": ["스태미나", "Stamina"],
	"hud_carry": ["운반 중", "Carrying"],
	"hud_alt": ["고도 %d m", "ALT %d m"],
	"hud_thermal": ["상승기류", "Thermal"],
	"year_n": ["%d년차", "Year %d"],
	"day_n": ["%d일째", "Day %d"],
	"dir_n": ["북", "N"],
	"dir_e": ["동", "E"],
	"dir_s": ["남", "S"],
	"dir_w": ["서", "W"],
	"season_spring": ["봄", "Spring"],
	"season_summer": ["여름", "Summer"],
	"season_autumn": ["가을", "Autumn"],
	"season_winter": ["겨울", "Winter"],
	"season_sub_spring": ["영역을 지키고 짝을 찾아라", "Hold your cliff. Find a mate."],
	"season_sub_summer": ["새끼들이 배고프다", "The chicks are hungry"],
	"season_sub_autumn": ["새끼에게 사냥을 가르쳐라", "Teach the young to hunt"],
	"season_sub_winter": ["버텨라", "Endure"],
	"weather_clear": ["맑음", "Clear"],
	"weather_cloudy": ["흐림", "Cloudy"],
	"weather_windy": ["강풍", "Windy"],
	"weather_rain": ["비", "Rain"],
	"weather_fog": ["안개", "Fog"],
	"weather_snow": ["눈", "Snow"],
	"weather_today": ["오늘 날씨: %s", "Today's weather: %s"],
	"prey_pigeon": ["비둘기", "Pigeon"],
	"prey_starling": ["찌르레기", "Starling"],
	"prey_sandpiper": ["도요새", "Sandpiper"],
	"prey_duck": ["오리", "Duck"],
	"prey_murrelet": ["바다쇠오리", "Ancient Murrelet"],
	"weather_storm": ["폭풍", "Storm"],
	"t_growth": ["성장", "Growth"],
	"sec": ["초", "s"],
	"prey_golden": ["황금 비둘기", "Golden Pigeon"],
	"ev_success": ["도전 성공!", "Challenge complete!"],
	"ev_timeout": ["시간 초과: %s", "Time's up: %s"],
	"ev_golden": ["황금 비둘기", "Golden Pigeon"],
	"ev_golden_d": ["빠르고 예민한 황금 비둘기가 나타났다. 달아나기 전에 잡아라", "A fast, wary golden pigeon appeared. Catch it before it leaves"],
	"ev_fail_golden": ["황금 비둘기가 멀리 날아가 버렸다", "The golden pigeon got away"],
	"ev_race": ["먹이 쟁탈전", "Hunting Race"],
	"ev_race_d": ["다른 매가 비둘기 떼를 노린다. 녀석보다 먼저 한 마리 잡아라", "Another falcon is eyeing a pigeon flock. Make a kill before it does"],
	"ev_fail_race": ["다른 매가 먼저 채 갔다", "The other falcon got there first"],
	"ev_thief": ["도둑 까마귀", "Thieving Crow"],
	"ev_thief_d": ["까마귀가 먹이를 노린다. 뺏기지 말고, 뺏기면 들이받아 되찾아라", "A crow wants your prey. Keep it, or ram the crow and snatch it back"],
	"ev_fail_thief": ["까마귀가 먹이를 가져가 버렸다", "The crow made off with your prey"],
	"ev_fast_kill": ["도전: 250 km/h 이상으로 사냥", "Challenge: kill at 250+ km/h"],
	"ev_fast_kill_d": ["높이 올라가 날개를 접고 내리꽂아라", "Climb high, tuck and stoop"],
	"ev_fail_fast_kill": ["", ""],
	"ev_climb": ["도전: 고도 400 m", "Challenge: reach 400 m"],
	"ev_climb_d": ["상승기류를 타고 올라가라", "Ride a thermal up"],
	"ev_fail_climb": ["", ""],
	"ev_two_kills": ["도전: 먹잇감 2마리", "Challenge: two kills"],
	"ev_two_kills_d": ["시간 안에 두 마리를 잡아라", "Make two kills in time"],
	"ev_fail_two_kills": ["", ""],
	"ev_speed_330": ["도전: 330 km/h 돌파", "Challenge: break 330 km/h"],
	"ev_speed_330_d": ["최대한 높이서 곧게 내리꽂아라", "Stoop straight down from as high as you can"],
	"ev_fail_speed_330": ["", ""],
	"ev_roll_dive": ["도전: 구르며 급강하", "Challenge: rolling stoop"],
	"ev_roll_dive_d": ["급강하 중에 A/D 두 번 눌러 세 바퀴 굴러라", "Double-tap A/D three times during a stoop"],
	"ev_fail_roll_dive": ["", ""],
	"mk_golden": ["황금 비둘기", "Golden pigeon"],
	"mk_hunter": ["경쟁자 매", "Rival hunter"],
	"mk_race": ["비둘기 떼", "Pigeons"],
	"mk_thief": ["도둑 까마귀", "Thief"],
	"growth_level": ["Lv.%d   경험 %d / %d   성장 포인트 %d", "Lv.%d   XP %d / %d   Points %d"],
	"level_up": ["레벨 업! Lv.%d", "Level up! Lv.%d"],
	"level_up_sub": ["성장 포인트 +1 — [P] 성장", "+1 growth point — [P] Growth"],
	"sk_dive": ["급강하", "Stoop"],
	"sk_dive_d": ["날개를 접었을 때 공기 저항이 줄어 최고 속도가 오른다", "Less drag when tucked — higher top speed"],
	"sk_wing": ["날개", "Wings"],
	"sk_wing_d": ["선회력과 빠져나오는 힘이 세진다", "Sharper turns and stronger pull-outs"],
	"sk_stamina": ["지구력", "Endurance"],
	"sk_stamina_d": ["스태미나 +30, 회복 +10%", "+30 stamina, +10% recovery"],
	"sk_eye": ["매의 눈", "Falcon Eye"],
	"sk_eye_d": ["먹잇감을 더 멀리서 찾고 조준 보조 거리가 늘어난다", "Spot prey farther away; longer aim assist"],
	"plumage": ["깃털 색", "Plumage"],
	"pl_default": ["기본", "Classic"],
	"pl_silver": ["은빛", "Silver"],
	"pl_rufous": ["적갈색", "Rufous"],
	"pl_dark": ["먹빛", "Dark"],
	"pl_white": ["해동청", "White"],
	"pl_lock_lv": ["잠김 Lv.%d", "Locked Lv.%d"],
	"pl_lock_quest": ["잠김 (전설)", "Locked (legend)"],
	"plumage_unlocked": ["새 깃털 색 해금: %s — [P] 성장에서 바꿀 수 있다", "New plumage unlocked: %s — change it in [P] Growth"],
	"ctrl_growth": ["P", "P"],
	"ctrl_growth_d": ["성장 (능력 강화, 깃털 색)", "Growth (upgrades, plumage)"],
	"storm_forecast": ["오늘은 날이 무겁다. 한낮에 폭풍이 올 것 같다", "The air is heavy today. A storm is coming around midday"],
	"storm_coming": ["폭풍이 몰려온다! 돌풍에 몸이 흔들린다", "The storm hits! Gusts shake you around"],
	"storm_flock": ["바다의 새떼가 폭풍을 피해 육지로 몰려온다 — 사냥 기회!", "Seabirds flee the storm toward land — hunting chance!"],
	"storm_over": ["폭풍이 잦아든다", "The storm is passing"],
	"fog_hint": ["짙은 안개: 먹잇감이 늦게 알아챈다. 기습하기 좋은 날", "Thick fog: prey notices you late. A good day for ambushes"],
	"prey_bat": ["박쥐", "Bat"],
	"island_new": ["새로운 섬", "New Island"],
	"island_hint_seabird": ["바닷새섬: 바다쇠오리는 수면 바로 위를 난다. 가까이 가면 잠수하니 위에서 단번에 꽂아라. 번식기 갈매기는 둥지를 지키려 덤빈다.", "Seabird Rock: murrelets skim the waves and dive when you get close — strike from above in one go. Nesting gulls defend the colony."],
	"island_hint_seals": ["물범 모래톱: 흰꼬리수리가 산다. 먹이를 들고 있으면 빼앗으러 온다. 빠르게 들이받으면 물러난다.", "Seal Sands: a white-tailed eagle lives here and will rob you. Ram it at speed to drive it off."],
	"island_hint_bats": ["박쥐섬: 여름·가을 해 질 녘이면 서쪽 동굴에서 박쥐 떼가 쏟아져 나온다.", "Bat Isle: at dusk in summer and autumn, bats pour out of the western sea cave."],
	"hint_islands": ["동쪽 바다 멀리 섬들이 보인다. 바다 위엔 상승기류가 없으니 높이를 벌고 건너자. [M] 지도", "Islands lie far out to the east. No thermals over the sea — gain height before crossing. [M] Map"],
	"mob_crow": ["까마귀 떼가 몰려와 괴롭힌다! 빠르게 날아 벗어나거나 들이받아라", "Crows are mobbing you! Outfly them or ram them"],
	"mob_gull": ["갈매기들이 둥지를 지키려 덤빈다!", "Gulls are defending their colony!"],
	"mob_driven": ["쫓아냈다", "Driven off"],
	"eagle_warn": ["흰꼬리수리가 먹이를 노린다! 빨리 벗어나라", "A white-tailed eagle is after your prey! Get away"],
	"eagle_stolen_sub": ["흰꼬리수리가 먹이를 채갔다", "The eagle snatched your prey"],
	"eagle_driven": ["수리를 쫓아냈다!", "Eagle driven off!"],
	"fox_warn": ["여우가 몰래 다가온다! 날아올라라(W)", "A fox is sneaking up! Take off (W)"],
	"fox_pounce": ["여우!", "Fox!"],
	"fox_pounce_sub": ["여우가 먹이를 물어 갔다", "The fox took your prey"],
	"bats_emerge": ["해가 진다. 박쥐섬 동굴에서 박쥐 떼가 나온다", "Dusk: bats are pouring out of the Bat Isle cave"],
	"mk_bats": ["박쥐 떼", "Bats"],
	"mk_eagle": ["흰꼬리수리", "Sea eagle"],
	"weak": ["약한 개체", "weak"],
	"mk_eyrie": ["둥지", "Eyrie"],
	"mk_mate": ["짝", "Mate"],
	"mk_rival": ["침입자", "Intruder"],
	"mk_owl": ["수리부엉이", "Eagle-owl"],
	# 안내
	"prompt_land": ["[E] 착지", "[E] Land"],
	"prompt_slow": ["속도를 줄이면 착지 가능 [S]", "Slow down to land [S]"],
	"prompt_rest": ["[E] 둥지", "[E] Eyrie"],
	"prompt_takeoff": ["[W]/[Space] 날아오르기", "[W]/[Space] Take off"],
	"prompt_eat": ["[Q] 먹기", "[Q] Eat"],
	"prompt_eat_air": ["[Q] 날면서 먹기  ", "[Q] Eat on the wing  "],
	"prompt_drop": ["[F] 떨어뜨리기", "[F] Drop"],
	"prompt_gift": ["[F] 짝에게 먹이 선물", "[F] Gift prey to mate"],
	"prompt_teach": ["[F] 새끼 위에서 떨어뜨려 사냥 가르치기", "[F] Drop above a youngster to teach"],
	"prompt_call": ["[R] 울음으로 부르기", "[R] Call"],
	"no_perch": ["근처에 앉을 곳이 없다 (속도를 줄이고 지면에 가까이)", "Nowhere to perch (slow down near the ground)"],
	"eat_need_perch": ["큰 먹잇감은 앉아서 먹어야 한다 [E]", "Land to eat big prey [E]"],
	"eating": ["먹는 중... %d%%", "Eating... %d%%"],
	"ate": ["냠", "Fed"],
	# 사냥
	"strike": ["STRIKE!", "STRIKE!"],
	"perfect": ["PERFECT STOOP!", "PERFECT STOOP!"],
	"bind": ["낚아챘다!", "Bound!"],
	"air_catch": ["공중 낚아채기!", "Mid-air catch!"],
	"bounced": ["튕겨났다!", "Glanced off!"],
	"bounced_sub": ["큰 먹잇감은 더 빠르게 내리꽂아야 한다", "Big prey needs a faster strike"],
	"dodged": ["피했다!", "Dodged!"],
	"dodged_sub": ["눈치챈 먹잇감은 느린 추격으론 못 잡는다 — 위에서 내리꽂아라", "Alert prey slips a slow chase — stoop from above"],
	"picked_up": ["%s를 주웠다", "Picked up the %s"],
	"stolen": ["빼앗겼다!", "Stolen!"],
	"stolen_sub": ["갈매기가 먹이를 채갔다", "A gull snatched your prey"],
	"gull_warn": ["갈매기가 먹이를 노린다! 빠르게 날아 따돌려라", "A gull is after your prey! Outfly it"],
	"gull_driven": ["갈매기를 쫓아냈다", "Gull driven off"],
	"crash": ["충돌!", "Crash!"],
	"blackout": ["정신을 잃었다", "You black out"],
	"blackout_sub": ["둥지에서 겨우 깨어났다", "You come to at the eyrie"],
	"starving": ["굶주리고 있다! 체력이 줄어든다", "Starving! Losing health"],
	"great_dive": ["멋진 급강하! %d km/h", "Great stoop! %d km/h"],
	# 영역/짝
	"rival_appears": ["침입자 매가 둥지 절벽을 노린다! 상승기류로 녀석보다 높이 올라가 들이받아라", "An intruder falcon wants your cliff! Climb a thermal above it and strike"],
	"rival_attack": ["위에서 급강하 공격! 옆으로 피해라(A/D)", "Stoop from above! Dodge sideways (A/D)"],
	"rival_open": ["침입자가 급강하 뒤 느려졌다 — 지금 들이받아라!", "The intruder is slow after its stoop — strike now!"],
	"mk_rival_open": ["지금 공격!", "Strike now!"],
	"hit_rival": ["적중!", "Hit!"],
	"got_hit": ["공격당했다!", "You were struck!"],
	"territory_won": ["영역을 지켜냈다!", "Territory held!"],
	"territory_won_sub": ["이 절벽은 이제 네 것이다", "This cliff is yours"],
	"mate_appears": ["짝 후보가 절벽 위에 나타났다! 멋진 급강하와 먹이 선물로 마음을 얻어라", "A potential mate circles the cliff! Win it with stoops and gifts of prey"],
	"mate_follows": ["짝 후보가 너를 따르기 시작했다. 둥지를 보여줘라", "Your suitor follows you now. Show it the eyrie"],
	"bond_display": ["구애 비행 %d km/h", "Courtship stoop %d km/h"],
	"bond_gift": ["먹이 선물!", "Food gift!"],
	"bond_eyrie": ["둥지 자리를 보여줬다", "Showed the eyrie"],
	"bond_call": ["울음을 주고받았다", "Called to each other"],
	"paired": ["짝을 맺었다!", "Paired for life!"],
	"paired_sub": ["%s와(과) 함께 살아간다", "You and %s are a pair"],
	"mate_returns": ["짝이 둥지로 돌아왔다", "Your mate has returned to the eyrie"],
	"mate_brought": ["짝이 새끼들에게 먹이를 물어왔다", "Your mate brought food to the chicks"],
	"mate_to_nest": ["짝이 먹이를 둥지로 가져갔다", "Your mate took the prey to the nest"],
	"mate_thanks": ["짝이 먹이를 받았다", "Your mate took the prey"],
	"mate_defended": ["짝이 수리부엉이를 막아냈다!", "Your mate fought off the eagle-owl!"],
	"fed_mate": ["알 품는 짝에게 먹이를 줬다", "Fed your brooding mate"],
	"eggs_laid": ["알 %d개를 낳았다", "%d eggs laid"],
	"hatched": ["알에서 새끼 %d마리가 깨어났다!", "%d chicks hatched!"],
	"no_chicks_year": ["올해는 새끼가 없다", "No chicks this year"],
	"fed_chicks": ["새끼들에게 먹이를 줬다", "Fed the chicks"],
	"fed_fledgling": ["어린 매에게 먹이를 줬다", "Fed a youngster"],
	"chick_starved": ["새끼 한 마리가 굶어 죽었다...", "A chick has starved..."],
	"owl_coming": ["수리부엉이가 둥지로 다가온다! 두 번 쳐서 쫓아내라", "An eagle-owl is coming for the nest! Strike it twice"],
	"hit_owl": ["적중!", "Hit!"],
	"owl_driven": ["수리부엉이를 쫓아냈다!", "The eagle-owl flees!"],
	"owl_took": ["수리부엉이가 %s를 채갔다...", "The eagle-owl took %s..."],
	"fledged": ["새끼 %d마리가 날개를 폈다! 이제 사냥을 가르쳐라", "%d young have fledged! Now teach them to hunt"],
	"lesson_ok": ["잘 받았다!", "Nice catch!"],
	"lesson_ok_sub": ["%s 사냥 실력 %d", "%s skill %d"],
	"lesson_fail": ["놓쳤다!", "Missed!"],
	"lesson_fail_sub": ["떨어지는 먹이를 다시 잡아 떨어뜨려 줘라", "Catch it again and drop it once more"],
	"independent": ["새끼 %d마리가 독립해 떠났다", "%d young have left to live on their own"],
	"offspring_survive": ["지난날 떠난 자식 %d마리가 아직 살아 있다", "%d of your offspring are still alive"],
	"growing_old": ["몸이 예전 같지 않다... 마지막 해일지도 모른다", "Your body is failing... this may be your last year"],
	"new_gen": ["%s — %d대째 송골매로 삶을 이어간다", "%s carries on as generation %d"],
	"murmuration": ["들판 위로 찌르레기 군무가 시작됐다", "A starling murmuration swirls over the fields"],
	"migration": ["도요새 떼가 갯벌에 도착했다!", "Sandpipers have arrived at the mudflats!"],
	# 힌트
	"hint_hungry": ["배가 고프다. 사냥하고 [Q]로 먹어라", "You're hungry. Hunt and press [Q] to eat"],
	"hint_night": ["밤에는 먹잇감이 적다. 둥지에서 [E]로 쉬어라", "Prey is scarce at night. Rest at the eyrie [E]"],
	"hint_chicks": ["새끼들이 배고파한다. 먹이를 들고 둥지에 착지하거나 둥지 위에서 [F]로 떨어뜨려라", "The chicks are hungry. Land at the eyrie with prey or drop it [F] above the nest"],
	"hint_crash": ["땅에 가까워지면 화면이 붉게 번쩍인다. 날개를 펴 속도를 줄이며 빠져나와라", "The screen flashes red near the ground. Open your wings and pull out"],
	# 프롤로그 (알에서 깨어나 어미에게 배우기)
	"pro_mother": ["어미 매", "Mother"],
	"pro_next": ["▶ 클릭", "▶ Click"],
	"pro_prompt_click": ["[클릭] 껍데기 쪼기", "[Click] Peck the shell"],
	"pro_goal_egg": ["알 깨기 — 쪼아라(클릭) %d / %d", "Break the egg — peck (click) %d / %d"],
	"pro_egg_1": ["…따뜻하다. 좁고 어둡다. 밖에서 누군가 부르는 소리가 들린다.", "...Warm. Tight and dark. Someone is calling from outside."],
	"pro_egg_2": ["껍데기에 금이 갔다! 조금만 더.", "The shell is cracking! A little more."],
	"pro_egg_3": ["빛이 새어 들어온다…!", "Light is leaking in...!"],
	"pro_hatch_1": ["드디어 깨어났구나, 아가.", "There you are, little one."],
	"pro_hatch_2": ["나는 네 어미란다. 이 바다 절벽이 우리 집이지.", "I'm your mother. This sea cliff is our home."],
	"pro_hatch_3": ["많이 먹고 튼튼하게 자라거라. 곧 하늘을 가르쳐 주마.", "Eat well and grow strong. Soon I'll teach you the sky."],
	"pro_weeks": ["몇 주 뒤…", "A few weeks later..."],
	"pro_flap_1": ["날개가 다 자랐구나. 오늘은 나는 법을 배울 날이다.", "Your wings are grown. Today you learn to fly."],
	"pro_flap_2": ["가고 싶은 쪽을 바라보고(마우스) 날갯짓해서(W) 날아올라라!", "Look where you want to go (mouse) and flap (W) to take off!"],
	"pro_goal_flap": ["날아오르기 — 날갯짓(W)", "Take off — flap (W)"],
	"pro_follow": ["잘했다! 나를 따라와라. 방향은 바라보는 쪽(마우스), 느려지면 날갯짓(W).", "Well done! Follow me. Steer by looking (mouse), flap (W) when you slow down."],
	"pro_follow_nag": ["어디 가니? 이쪽이다! 나를 바라봐라(마우스).", "Where are you going? This way! Look at me (mouse)."],
	"pro_goal_follow": ["어미 따라가기", "Follow your mother"],
	"pro_thermal": ["여기다. 따뜻한 공기가 솟는 곳이지. 기둥 안에 들어와서 마우스에서 손을 떼 보렴. 몸이 알아서 빙빙 돌며 올라간다.", "Here. Warm air rises here. Get inside the column and let go of the mouse — your body will circle up on its own."],
	"pro_thermal_nag": ["기둥에서 벗어났다. 나를 보고 다시 들어와서 손을 떼라(마우스).", "You slipped out. Look at me, get back in and let go (mouse)."],
	"pro_takeoff_nag": ["다시 날아올라라(W).", "Take off again (W)."],
	"pro_goal_thermal": ["상승기류 타고 150m까지 — 지금 %d m", "Ride the thermal to 150 m — now %d m"],
	"pro_stoop_1": ["이제 우리 매만 가진 비밀을 알려주마. 날개를 접으면 돌처럼 떨어지며 무엇보다 빨라진다.", "Now, our secret. Fold your wings and you fall like a stone — faster than anything alive."],
	"pro_stoop_2": ["아래를 보고(마우스) 날개를 접어라(스페이스 누르기)! 180km/h를 넘기면 땅에 닿기 전에 날개를 펴라(스페이스 떼기).", "Look down (mouse) and fold your wings (hold Space)! Past 180 km/h, open them before the ground (release Space)."],
	"pro_goal_stoop": ["급강하로 180km/h 넘기고 빠져나오기 — 최고 %d km/h", "Stoop past 180 km/h and pull out — best %d km/h"],
	"pro_stoop_ok": ["바로 그거다! 그게 송골매의 급강하다.", "That's it! That's the peregrine's stoop."],
	"pro_crash": ["너무 늦게 폈구나! 괜찮다. 상승기류로 다시 올라가 해 보자.", "Too late! It's all right. Climb the thermal and try again."],
	"pro_crash_soft": ["조심해라! 다시 날아올라라(W).", "Careful! Take off again (W)."],
	"pro_goal_reclimb": ["상승기류로 다시 올라가기 (노란 표식)", "Climb the thermal again (yellow marker)"],
	"pro_catch": ["이번엔 먹이 받기다. 내가 먹이를 떨어뜨리마. 떨어지는 먹이를 향해 날아가 공중에서 받아라.", "Now, catching. I'll drop some food. Fly at it as it falls and snatch it mid-air."],
	"pro_catch_now": ["지금이다! 받아라!", "Now! Catch it!"],
	"pro_catch_pickup": ["떨어졌구나. 속도를 줄이고(S) 천천히 스치듯 날아가 주워라.", "It fell. Slow down (S) and skim over it to pick it up."],
	"pro_catch_again": ["여기 하나 더 있다. 다시 해 보자.", "Here's another. Try again."],
	"pro_catch_ok": ["잘 받았다!", "Nice catch!"],
	"pro_goal_catch": ["떨어지는 먹이 받기", "Catch the falling food"],
	"pro_eat": ["이제 바위나 둥지 근처에서 속도를 줄이고(S) 앉아(E) 먹어라(Q).", "Now slow down (S) near a rock or the eyrie, land (E) and eat (Q)."],
	"pro_goal_eat": ["앉아서(E) 먹기(Q)", "Land (E) and eat (Q)"],
	"pro_eat_ok": ["배가 부르니 힘이 나지? 이제 진짜 사냥이다.", "Feeling stronger? Now, a real hunt."],
	"pro_hunt_1": ["저기 비둘기들이 보이느냐? 멀리 있는 먹잇감은 매의 눈으로 찾아라(C 누르기).", "See those pigeons? Find distant prey with falcon eye (hold C)."],
	"pro_hunt_2": ["높이 올라가서 날개를 접고(스페이스) 노란 ◇를 노려라. ◇는 먹잇감과 부딪힐 곳이다!", "Get above them, fold your wings (Space) and aim at the yellow ◇ — that's where you'll meet it!"],
	"pro_goal_hunt": ["비둘기 사냥하기", "Hunt a pigeon"],
	"pro_hunt_ok": ["해냈구나! 이제 너는 진짜 매다.", "You did it! Now you're a true falcon."],
	"pro_home": ["훌륭하다. 둥지로 돌아와 앉아라(E).", "Well done. Come back to the eyrie and land (E)."],
	"pro_goal_home": ["둥지로 돌아가 앉기(E)", "Return to the eyrie and land (E)"],
	"pro_bye_1": ["이제 너는 혼자서도 살 수 있다.", "You can live on your own now."],
	"pro_bye_2": ["이 절벽은 이제 네 것이다. 누가 넘보면 쫓아내고, 봄이 오면 짝을 찾아 새끼를 키워라.", "This cliff is yours. Drive off anyone who wants it, and in spring find a mate and raise young."],
	"pro_bye_3": ["잘 있거라, 아가. 하늘이 늘 너와 함께하길.", "Farewell, little one. May the sky be with you."],
	"pro_year_later": ["1년 뒤, 봄", "One year later — spring"],
	"pro_mk_perch": ["앉을 곳", "Perch"],
	"pro_mk_food": ["먹이", "Food"],
	"ng_tutorial": ["시작", "Start"],
	"ng_tut_on": ["알에서부터 (튜토리얼)", "From the egg (tutorial)"],
	"ng_tut_off": ["튜토리얼 건너뛰기", "Skip tutorial"],
	"p_skip_tut": ["튜토리얼 건너뛰기", "Skip tutorial"],
	# 목표
	"obj_territory": ["영역 지키기: 침입자 매 쫓아내기 (%d/%d)", "Defend territory: drive off the intruder (%d/%d)"],
	"obj_mate": ["짝 찾기: 구애 급강하·먹이 선물 (유대 %d/100)", "Find a mate: courtship stoops & gifts (bond %d/100)"],
	"obj_eggs_soon": ["짝이 곧 알을 낳는다 (다음 날 아침)", "Your mate will lay eggs (next morning)"],
	"obj_incubate": ["알 품는 짝에게 먹이 주기 (%d/2)", "Feed your brooding mate (%d/2)"],
	"obj_summer_alone": ["여름 사냥철 — 힘을 길러라", "Summer — grow strong"],
	"obj_feed_chicks": ["새끼 %d마리 먹이기 (평균 포만감 %d)", "Feed %d chicks (avg food %d)"],
	"obj_owl": ["수리부엉이 쫓아내기 (%d/2)", "Drive off the eagle-owl (%d/2)"],
	"obj_autumn_alone": ["가을 — 겨울을 대비해 배를 채워라", "Autumn — fatten up for winter"],
	"obj_teach": ["사냥 가르치기: 새끼 위에서 먹이 떨어뜨리기 (%d/%d)", "Teach hunting: drop prey above the young (%d/%d)"],
	"obj_winter": ["겨울 버티기 (%d/%d일)", "Survive winter (day %d/%d)"],
	"obj_eat": ["배를 채워라 (포만감 %d)", "Eat something (food %d)"],
	# 둥지 메뉴
	"r_title": ["둥지", "Eyrie"],
	"r_sleep": ["아침까지 자기 (저장)", "Sleep until morning (save)"],
	"r_nap": ["한 시간 쉬기", "Rest for an hour"],
	"r_save": ["저장", "Save"],
	"r_fly": ["날아오르기", "Take off"],
	"r_status": ["%s · %d살 · 체력 %d · 포만감 %d", "%s · age %d · health %d · food %d"],
	"r_mate": ["짝: %s", "Mate: %s"],
	"r_eggs": ["알 %d개", "%d eggs"],
	"r_chick": ["새끼 %s — 포만감 %d", "Chick %s — food %d"],
	"r_fledgling": ["어린 매 %s — 실력 %d, 포만감 %d", "Youngster %s — skill %d, food %d"],
	"r_sleep_later": ["잠은 오후 4시 이후에 잘 수 있다", "You can sleep after 4 PM"],
	# 결산
	"sum_title": ["%d년차 결산", "End of Year %d"],
	"sum_name": ["이름", "Name"],
	"sum_age": ["나이", "Age"],
	"sum_prey_year": ["올해 사냥", "Kills this year"],
	"sum_prey_total": ["평생 사냥", "Lifetime kills"],
	"sum_top_speed": ["최고 속도", "Top speed"],
	"sum_perfect": ["완벽한 일격", "Perfect stoops"],
	"sum_fledged": ["올해 독립시킨 새끼", "Young raised this year"],
	"sum_generation": ["세대", "Generation"],
	"sum_note": ["봄이 오면 짝이 돌아오고, 누군가는 또 이 절벽을 노릴 것이다.", "Spring will bring your mate back — and someone else will want this cliff."],
	"sum_note_old": ["날개가 무겁다. 다음 봄을 맞을 수 있을까.", "Your wings feel heavy. Will you see another spring?"],
	"sum_next": ["다음 해로", "Next year"],
	# 죽음
	"d_title": ["%s의 삶이 끝났다", "%s's life has ended"],
	"cause_starve": ["굶주림으로 쓰러졌다.", "Died of starvation."],
	"cause_crash": ["너무 빠르게 땅에 부딪혔다.", "Hit the ground too fast."],
	"cause_rival": ["침입자 매와의 싸움에서 쓰러졌다.", "Fell fighting an intruder."],
	"cause_old": ["늙은 날개를 접고 조용히 잠들었다.", "Folded old wings and slept for good."],
	"d_lineage": ["혈통", "Bloodline"],
	"d_line": ["%d대 %s — %d살, 사냥 %d, 키운 새끼 %d", "Gen %d %s — age %d, kills %d, young raised %d"],
	"d_choose": ["살아 있는 자식으로 삶을 이어간다:", "Continue as one of your living offspring:"],
	"d_kid": ["%s (%s) · 사냥 실력 %d · %d년차에 독립", "%s (%s) · skill %d · left in year %d"],
	"d_end": ["살아남은 자식이 없다. 혈통이 여기서 끊겼다.", "No offspring survive. The bloodline ends here."],
	"d_title_btn": ["타이틀로", "To Title"],
	"d_later": ["나중에 이어가기 (타이틀로)", "Continue later (to title)"],
}


func t(key: String) -> String:
	var e = S.get(key)
	if e == null:
		return key
	return e[0] if lang == "ko" else e[1]
